# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.5/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ghaz/TokenGranterWrapper

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ghaz/TokenGranterWrapper

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ghaz/TokenGranterWrapper/CMakeFiles /Users/ghaz/TokenGranterWrapper//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ghaz/TokenGranterWrapper/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named token_granter_shared

# Build rule for target.
token_granter_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 token_granter_shared
.PHONY : token_granter_shared

# fast build rule for target.
token_granter_shared/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/token_granter_shared.dir/build.make CMakeFiles/token_granter_shared.dir/build
.PHONY : token_granter_shared/fast

#=============================================================================
# Target rules for targets named token_granter

# Build rule for target.
token_granter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 token_granter
.PHONY : token_granter

# fast build rule for target.
token_granter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/token_granter.dir/build.make CMakeFiles/token_granter.dir/build
.PHONY : token_granter/fast

src/token_granter.o: src/token_granter.cpp.o
.PHONY : src/token_granter.o

# target to build an object file
src/token_granter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/token_granter_shared.dir/build.make CMakeFiles/token_granter_shared.dir/src/token_granter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/token_granter.dir/build.make CMakeFiles/token_granter.dir/src/token_granter.cpp.o
.PHONY : src/token_granter.cpp.o

src/token_granter.i: src/token_granter.cpp.i
.PHONY : src/token_granter.i

# target to preprocess a source file
src/token_granter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/token_granter_shared.dir/build.make CMakeFiles/token_granter_shared.dir/src/token_granter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/token_granter.dir/build.make CMakeFiles/token_granter.dir/src/token_granter.cpp.i
.PHONY : src/token_granter.cpp.i

src/token_granter.s: src/token_granter.cpp.s
.PHONY : src/token_granter.s

# target to generate assembly for a file
src/token_granter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/token_granter_shared.dir/build.make CMakeFiles/token_granter_shared.dir/src/token_granter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/token_granter.dir/build.make CMakeFiles/token_granter.dir/src/token_granter.cpp.s
.PHONY : src/token_granter.cpp.s

src/token_granter_bindings.o: src/token_granter_bindings.cpp.o
.PHONY : src/token_granter_bindings.o

# target to build an object file
src/token_granter_bindings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/token_granter.dir/build.make CMakeFiles/token_granter.dir/src/token_granter_bindings.cpp.o
.PHONY : src/token_granter_bindings.cpp.o

src/token_granter_bindings.i: src/token_granter_bindings.cpp.i
.PHONY : src/token_granter_bindings.i

# target to preprocess a source file
src/token_granter_bindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/token_granter.dir/build.make CMakeFiles/token_granter.dir/src/token_granter_bindings.cpp.i
.PHONY : src/token_granter_bindings.cpp.i

src/token_granter_bindings.s: src/token_granter_bindings.cpp.s
.PHONY : src/token_granter_bindings.s

# target to generate assembly for a file
src/token_granter_bindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/token_granter.dir/build.make CMakeFiles/token_granter.dir/src/token_granter_bindings.cpp.s
.PHONY : src/token_granter_bindings.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... token_granter"
	@echo "... token_granter_shared"
	@echo "... src/token_granter.o"
	@echo "... src/token_granter.i"
	@echo "... src/token_granter.s"
	@echo "... src/token_granter_bindings.o"
	@echo "... src/token_granter_bindings.i"
	@echo "... src/token_granter_bindings.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

