name: CMake Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            suffix: so
          - os: macos-latest
            suffix: dylib

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt-get update
            sudo apt install curl
            sudo apt-get install -y libcurl4-openssl-dev
          else
            brew install curl
          fi

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        run: cmake $GITHUB_WORKSPACE -B ${{runner.workspace}}/build

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config Release

      - name: Upload Artifact Shared
        uses: actions/upload-artifact@v2
        with:
          name: library-${{ matrix.os }}-${{ matrix.suffix }}
          path: ${{runner.workspace}}/build/libtoken_granter_shared.${{ matrix.suffix }}

      - name: Upload Artifact Pybindings
        uses: actions/upload-artifact@v2
        with:
          name: library-${{ matrix.os }}-${{ matrix.suffix }}
          path: ${{runner.workspace}}/TokenGranterWrapper/token_granter_wrapper/token_granter.*.so

      - name: Install Packages
        run: python -m pip install cibuildwheel twine build

      - name: Clean project directory
        run: find . -path ./include -prune -o -type f \( -name "*.so" -o -name "*.c" -o -name "*.o" \) -delete

      - name: Build wheels
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            python -m cibuildwheel --platform linux --output-dir wheelhouse
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            python -m cibuildwheel --platform macos --output-dir wheelhouse
          fi
        env:
          CIBW_SKIP: cp38-* cp39-* cp310-* cp311=* cp312=*
          CIBW_BUILD: cp311*

      - name: Publish to PyPI
        run: python -m twine upload --repository-url https://pypi.ghaz.dev:440 wheelhouse/*.whl --verbose
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
